# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.TextField(default='Player1'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.TextField(default='Player1'),
        ),
        migrations.AddField(
            model_name='game',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
