# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180322_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score2',
        ),
        migrations.AddField(
            model_name='game',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
